### ISSUE TITLE
Installation issue: Dependenccy conflict

### ISSUE THREAD

**Issue by nabinkhadka** [dataqa/dataqa#2]
Thank you for the library.

I am unable to install it locally:

Environment:
MacOSX (Big Sur 11.5.2)
Used python virtualenv (python v3.9.6)

```
(vtest) dev@npl:(~/Downloads) % pip install dataqa

Collecting dataqa
  Downloading dataqa-1.0.2-py3-none-any.whl (16.1 MB)
     |████████████████████████████████| 16.1 MB 5.4 MB/s
Collecting pandas==0.25.0
  Downloading pandas-0.25.0.tar.gz (12.6 MB)
     |████████████████████████████████| 12.6 MB 1.2 MB/s
Collecting requests==2.23.0
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 6.3 MB/s
Collecting scikit-learn==0.21.3
  Downloading scikit-learn-0.21.3.tar.gz (12.2 MB)
     |████████████████████████████████| 12.2 MB 6.0 MB/s
Collecting dataqa
  Downloading dataqa-1.0.1-py3-none-any.whl (16.1 MB)
     |████████████████████████████████| 16.1 MB 5.6 MB/s
ERROR: Cannot install dataqa==1.0.1 and dataqa==1.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    dataqa 1.0.2 depends on dataqa-es==0.0.2
    dataqa 1.0.1 depends on dataqa-es==0.0.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 21.1.2; however, version 21.2.4 is available.
You should consider upgrading via the '/Users/nabin/Downloads/vtest/bin/python -m pip install --upgrade pip' command.
```

**Comment by dataqa** [comment]
Hi, could you tell me what python version and macos version you're on? Thanks!

**Comment by nabinkhadka** [comment]
@dataqa I edited it above.

**Comment by dataqa** [comment]
Hi, thanks for your patience. I had done all my development with an older version of python (3.7), and encountered some issues when trying to install from higher versions. You have 2 options:
* can you install this from a python version 3.7? This would be much easier.
* Otherwise, you can install it for 3.8 or 3.9, but it will have issues when installing one of the dependencies (scikit-learn==0.21.3) on macOS. For some reason, this did not happen on my linux machine. For that, I have successfully managed to install it by following the steps in the official scikit-learn guide on how to compile from source (it's in the README). Basically, the steps are:
   * make sure you have the macOS command line tools (`xcode-select --install`)
   * `brew install libomp`
   * ```export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
          export CPPFLAGS="$CPPFLAGS -Xpreprocessor -fopenmp"
          export CFLAGS="$CFLAGS -I/usr/local/opt/libomp/include"
          export CXXFLAGS="$CXXFLAGS -I/usr/local/opt/libomp/include"
          export LDFLAGS="$LDFLAGS -Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"```
  * `pip install scikit-learn==0.21.3 `
  * `pip install dataqa`
  * `pip install networkx==2.5`

**Comment by nabinkhadka** [comment]
Worked with python3.7.9. Thank you!
