### ISSUE TITLE
Resolve the python 3.8+ installation issue

### ISSUE THREAD

**Issue by talolard** [dataqa/dataqa#9]
The README specifies extra work if I'm using Python >3.7. 
I don't want to do extra work or even check what version of python I'm on. For potential users, having to deal with installation hassle is a turn off.

You, as package maintainer, can make my life easier and get more users by overriding snorkels dependency on networkx 2.5 in the setup.py file

**Comment by dataqa** [comment]
Hey, you're right again :-). Unfortunately, I cannot override the dependency on the setup.py file because the latest dependecy resolver shipped with "pip" finds the requirements are incompatible. I have made changed the explanations in the README though, and now, it's just a matter of passing a flag to pip when installing the tool with Python 3.9. Anything below 3.9 does not need any extra steps. I will also try to sort this out by tracking the github issue raised against the offending package (snorkel).
